User can Register for an account
CraftAcademy/fake_news_client pull request #20
Opened 2019-11-02 17:05 UTC by lucamarial

[PT-link](https://www.pivotaltracker.com/story/show/169263979)

## This PR contains
```
As a User,
In order to access article content on the news app,
I would like to be able to register for an account on the site.
```

## PR content
- Sign up functionality
- Feature test
  - Happy Path
  - Sad Path
- Fixture file
- Updates redux user registration attributes

## What I've learned
- Deeper understanding of redux
- How to catch errors
- How to work with debuggers

2019-11-02 17:06 UTC, jonas-masharqa approved these changes

2019-11-02 17:08 UTC, clalil approved these changes

2019-11-02 17:08 UTC, jonas-masharqa approved these changes

2019-11-02 18:21 UTC, AlexSaxena approved these changes

2019-11-04 11:13 UTC, GergKllai1 reviewed
Couple of things that can be refactored later:
- Specific Articles should not be handled inside the article list component. They should be a separate component where you navigate with a Link, fetch the article from server and display it. That is important for sharing purposes.
- In route responses you don't have to use a fixture file, you can pass down a javascript object as well. Cypress will convert it to json for you. That can help you reduce your fixture file size for small responses for instance cannot_create_article.json
- You should make use of the index support cypress file to refactor your tests. Instead of having your getarticle route in every test file you can put that there.

2019-11-04 11:14 UTC, GergKllai1 requested changes

2019-11-04 11:14 UTC, GergKllai1 commented on cypress/integration/UserCanSignupToApplication.spec.js
> +      // }
Remove commented out code

2019-11-04 11:28 UTC, clalil commented on cypress/integration/UserCanSignupToApplication.spec.js
> +      // }
Done!

2019-11-04 11:42 UTC, GergKllai1 approved these changes

2019-11-04 11:44 UTC, shsteindorsson approved these changes

2019-11-04 12:04 UTC, merged