User can buy a subscription
CraftAcademy/fake_news_client pull request #22
Opened 2019-11-04 15:56 UTC by clalil

# User can buy a subscription
[PT-link](https://www.pivotaltracker.com/story/show/169253777)

2019-11-05 17:35 UTC, clalil commented on src/Components/SignUp.js
> +        debugger;
Thank you! Removed!

2019-11-05 17:43 UTC, shsteindorsson approved these changes

2019-11-05 18:10 UTC, oliverochman requested changes

2019-11-05 18:10 UTC, oliverochman commented on cypress/fixtures/successful_payment.json
> +    "message": "Transaction successful"
indentation :)

2019-11-05 18:10 UTC, oliverochman commented on cypress/integration/LoggedInUserCanBuyASubscription.spec.js
> +    cy.signup_user(
please use `camelCase` when writing methods in js.

2019-11-05 18:10 UTC, oliverochman commented on src/App.js
> +          {this.props.currentUser.isSignedIn ? <PaymentForm /> : <Redirect to="/" />}
research `import { generateRequireSignInWrapper } from 'redux-token-auth';`

tex
https://github.com/CraftAcademy/Glocal_news-client/blob/development/src/App.js

2019-11-05 18:17 UTC, clalil commented on cypress/fixtures/successful_payment.json
> +    "message": "Transaction successful"
Solved!

2019-11-05 18:17 UTC, clalil commented on cypress/integration/LoggedInUserCanBuyASubscription.spec.js
> +    cy.signup_user(
Of course!

2019-11-05 18:37 UTC, clalil commented on src/App.js
> +          {this.props.currentUser.isSignedIn ? <PaymentForm /> : <Redirect to="/" />}
Of course!

2019-11-06 08:24 UTC, clalil commented on src/App.js
> +          {this.props.currentUser.isSignedIn ? <PaymentForm /> : <Redirect to="/" />}
Update: we found this was out of scope since the PR is about payment and we would have to change the entire navbar.

2019-11-06 08:39 UTC, oliverochman approved these changes

2019-11-06 08:40 UTC, merged